# Generated by Django 3.2.7 on 2021-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aquiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('number_of_quesstions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Duration of time in minutes')),
                ('required_score_to_pass', models.IntegerField(help_text='Required score to pass')),
                ('difficulty', models.CharField(choices=[('H', 'Hard'), ('M', 'Medium'), ('E', 'Easy')], max_length=6)),
            ],
        ),
    ]
